name: Exercises
on:
  - push
  - pull_request

jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-14']
    name: Rakudo Star on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Install Rakudo Star with choco
        if: runner.os == 'Windows'
        run: >
          choco install rakudostar;
          echo "C:\rakudo\bin;C:\rakudo\share\perl6\site\bin"
          | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Rakudo Star with brew
        if: runner.os == 'macOS'
        run: brew install rakudo-star

      - name: Rakudo Star tests with prove6
        if: runner.os != 'Linux'
        run: prove6 --jobs 2 (Get-Item -Path exercises/practice/*/.meta/solutions/)
        shell: pwsh

      - name: Rakudo Star tests with docker run
        if: runner.os == 'Linux'
        uses: docker://rakudo-star:latest
        with:
          args: /bin/bash -c "prove6 --jobs 2 /github/workspace/exercises/practice/*/.meta/solutions/"
